AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/*'
    - 'alfonsox.gemspec'
    - 'Gemfile'
    - 'Gemfile.lock'

Metrics/LineLength:
  Max: 120

Style/RedundantSelf:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
    Enabled: false