before_install:
- sudo apt-get update
- sudo apt-get install -y hunspell libhunspell-dev build-essential
env:
  global:
  - CC_TEST_REPORTER_ID=c6f6f48c884645f1b5cf6adaccd1c837b19989c5b88e430e5c217ca93cbe07dd
  - COVERAGE=true
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script: "bundle exec rake test"
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT